# Generated by Django 5.2.6 on 2025-09-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('image', models.ImageField(upload_to='post_images/')),
                ('scheduled_time', models.DateTimeField(db_index=True)),
                ('target_platforms', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHING', 'Publishing'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
    ]
